using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Configuration;


namespace SocioBoardInvitationMailSender.Helper
{
    class MailSender
    {
        public static string SendIvitationMail(string UserName, string toEmail, string mandrilEmail, string mandrilPass, string SenderName)
        {
            try
            {
                string html = "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">" +
                "<title>Freshmail Responsive E-mail Template - Mixed Layout Blue</title><style type=\"text/css\">html {width: 100%}::-moz-selection {background: #eb5600;color: #fff}::selection {background: #eb5600;color: #fff}" +
                "body {background-color: #f8f8f8;margin: 0;padding: 0}.ReadMsgBody {width: 100%;background-color: #f8f8f8}.ExternalClass {width: 100%;background-color: #f8f8f8}a {color: #eb5600;text-decoration: none;font-weight: 400;font-style: normal}" +
                "a:hover {color: #aaa;text-decoration: underline;font-weight: 400;font-style: normal}a.heading-link {text-decoration: none;font-weight: 400;font-style: normal}a.heading-link:hover {text-decoration: none;font-weight: 400;font-style: normal}" +
                "p,div {margin: 0!important}table {border-collapse: collapse}@media only screen and (max-width: 640px) {table table {width: 100%!important}td[class=full_width] {width: 100%!important}" +
                "div[class=div_scale] {width: 440px!important;margin: 0 auto!important}table[class=table_scale] {width: 440px!important;margin: 0 auto!important}td[class=td_scale] {width: 440px!important;margin: 0 auto!important}" +
                "img[class=img_scale] {width: 100%!important;height: auto!important}img[class=divider] {width: 440px!important;height: 2px!important}table[class=spacer] {display: none!important}td[class=spacer] {display: none!important}" +
                "td[class=center] {text-align: center!important}table[class=full] {width: 400px!important;margin-left: 20px!important;margin-right: 20px!important}img[class=divider] {width: 100%!important;height: 1px!important}}@media only screen and (max-width: 479px) {table table {width: 100%!important}td[class=full_width] {width: 100%!important}" +
                "div[class=div_scale] {width: 280px!important;margin: 0 auto!important}table[class=table_scale] {width: 280px!important;margin: 0 auto!important}td[class=td_scale] {width: 280px!important;margin: 0 auto!important}img[class=img_scale] {width: 100%!important;height: auto!important}" +
                "img[class=divider] {width: 280px!important;height: 2px!important}table[class=spacer] {display: none!important}td[class=spacer] {display: none!important}td[class=center] {text-align: center!important}table[class=full] {width: 240px!important;margin-left: 20px!important;margin-right: 20px!important}" +
                "img[class=divider] {width: 100%!important;height: 1px!important}}</style>" +
                "<style type=\"text/css\"></style></head><body bgcolor=\"#f8f8f8\"><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin-top: 20px;\"><tbody><tr>" +
                "<td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                "<tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table><table class=\"table_scale\" width=\"600\" bgcolor=\"#ffffff\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                "<tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\"><table class=\"full\" align=\"left\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">" +
                "<tbody><tr><td class=\"center\" align=\"left\" style=\"padding: 0px; text-transform: uppercase; font-family: Lucida Sans Unicode; color:#666666; font-size:24px; line-height:34px;\"> <span> <a href=\"#\" style=\"color:#eb5600;\"> <img src=\"http://www.socioboard.com/Themes/Socioboard/Contents/img/logo.png\" alt=\"logo\" width=\"250\" height=\"60\" border=\"0\" style=\"display: inline;\"> </a> </span> </td></tr></tbody>" +
                "</table><table width=\"25\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td width=\"100%\" height=\"30\"></td></tr>" +
                "</tbody></table><table class=\"full\" align=\"right\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody>" +
                "<tr><td class=\"center\" align=\"right\" style=\"margin: 0; padding-top: 10px; text-transform: uppercase; font-size: 10px; color:#666666; font-family: Lucida Sans Unicode; line-height: 30px;  mso-line-height-rule: exactly;\"> <span> call us: +1 408 5209502, +91 80 41660003</span>" +
                "</td></tr></tbody></table></td><td class=\"spacer\" width=\"30\"></td></tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table class=\"table_scale\" width=\"600\" bgcolor=\"#eb5600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\">" +
                "<table width=\"600\" background=\"images/featured-bg.png\" bgcolor=\"#eb5600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"600\" valign=\"middle\" style=\"padding: 0px;\"><table class=\"full\" align=\"center\" width=\"540\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr><tr><td class=\"center\" align=\"center\" style=\"margin: 0; padding-bottom:15px; margin:0; text-transform: uppercase; font-family: Lucida Sans Unicode; font-size: 32px; color: #ffffff; line-height: 42px;mso-line-height-rule: exactly;\"> <span> HI [name],</span></td></tr><tr><td class=\"center\" align=\"center\" style=\"margin: 0; padding-bottom:15px; margin:0; text-transform: uppercase; font-family: Lucida Sans Unicode; font-size: 18px; color: #ffffff; line-height: 30px;mso-line-height-rule: exactly;\">" +
                "<span>your friend [SenderName] has invited you to try Socioboard.</span></td></tr><tr><td class=\"center\" align=\"center\" style=\"margin: 0; padding:0px; margin:0; font-size:13px ; color:#ffffff; font-family: Helvetica, Arial, sans-serif; line-height: 25px;mso-line-height-rule: exactly;\">" +
                "<span> Socioboard is a FREE and open source social media management and engagement platform which helps you generate more sales and acquire new customers on Social Media.<br>Thousands of social media enthusiasts like you are using Socioboard daily to interact and engage your audience in unique effortless ways.<br>Try Socioboard today and take your business to newer heights.<br> Do share your Socioboarding experience with us at <a href=\"http://www.socioboard.com/Index/contact\" target=\"_blank\" style=\"color:#ffeda4;\">http://www.socioboard.com/Index/contact</a> . <br>" +
                "You can also write to us on <strong>support@socioboard.com</strong> or join us on Skype at <strong>socioboard.support</strong>. <br>Happy Socioboarding! <br>Thanks </span> </td></tr><tr><td align=\"center\" valign=\"middle\" style=\"padding-top: 20px;\"><table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#ffffff\" style=\"margin: 0;\"><tbody><tr><td align=\"center\" valign=\"middle\" bgcolor=\"#ffffff\" style=\"padding: 8px 20px; text-transform: uppercase; color:#666666; font-size:18px ; color:#ffffff; font-family: Helvetica, Arial, sans-serif; line-height: 28px; mso-line-height-rule: exactly;\"> <a href=\"http://www.socioboard.com/\" target=\"_blank\" style=\"font-weight: normal; color:#444444; \"> Click here to use Socioboard absolutely free! </a> </td></tr></tbody></table></td></tr><tr>" +
                "<td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody>" +
                "<tr><td width=\"100%\"><table bgcolor=\"#dddddd\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td</tr></tbody></table><table class=\"table_scale\" width=\"600\" bgcolor=\"#dddddd\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\">" +
                "<table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\"><table class=\"full\" align=\"left\" width=\"160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"left\" style=\"margin: 0; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 24px;\"> <span> <a href=\"http://www.socioboard.com\" target=\"_blank\" style=\"color:#eb5600;\"> <img class=\"img_scale\" src=\"http://www.socioboard.com/Themes/Socioboard/Contents/img/slidegraph.png\" alt=\"portfolio_1\" width=\"160\" height=\"100\" border=\"0\" style=\"display: block;\"> </a> </span> </td></tr></tbody></table><table width=\"30\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td width=\"100%\" height=\"30\"></td>" +
                "</tr></tbody></table><table class=\"full\" align=\"left\" width=\"160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"left\" style=\"margin: 0; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 24px;\"> <span> <a href=\"http://www.socioboard.com\" target=\"_blank\" style=\"color:#eb5600;\"> <img class=\"img_scale\" src=\"http://www.socioboard.com/Themes/Socioboard/Contents/img/ssp/phone-banner.png\" alt=\"portfolio_2\" width=\"160\" height=\"100\" border=\"0\" style=\"display: block;\"> </a> </span> </td></tr></tbody></table><table width=\"20\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody>" +
                "<tr><td width=\"100%\" height=\"30\"></td></tr></tbody></table><table class=\"full\" align=\"right\" width=\"160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"left\" style=\"margin: 0; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 24px;\"> <span> <a href=\"http://www.socioboard.com\" target=\"_blank\" style=\"color:#eb5600;\"> <img class=\"img_scale\" src=\"http://www.socioboard.com/Themes/Socioboard/Contents/img/ssp/img-1.png\" alt=\"portfolio_3\" width=\"160\" height=\"100\" border=\"0\" style=\"display: block;\"> </a> </span> </td></tr></tbody></table></td><td class=\"spacer\" width=\"30\"></td>" +
                "</tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#dddddd\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"40\">&nbsp;</td></tr>" +
                "</tbody></table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\">" +
                "<table class=\"table_scale\" width=\"600\" bgcolor=\"#ffffff\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                "<tbody><tr><td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\"><table class=\"full\" align=\"left\" width=\"540\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"center\" style=\"padding-bottom: 10px; text-transform: uppercase; font-family: Lucida Sans Unicode; color:#666666; font-size:24px; line-height:34px; mso-line-height-rule: exactly;\"> <span> Our Esteemed Clientele ... </span> </td></tr></tbody></table><table class=\"full\" align=\"center\" width=\"160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody>" +
                "<tr><td class=\"center\" align=\"center\" style=\"margin: 0; padding: 0px; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 24px;\"> <span> <a target=\"_blank\" href=\"#\" style=\"color:#eb5600;\"> <img src=\"http://www.socioboard.com/Themes/Socioboard/Contents/img/re_store_logos.png\" alt=\"blue\" width=\"600\" height=\"200\" border=\"0\" style=\"display: inline;\"> </a></span> </td></tr></tbody></table></td><td class=\"spacer\" width=\"30\"></td></tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"40\">&nbsp;</td></tr></tbody></table>" +
                "</td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                "<tbody><tr><td width=\"100%\"><table class=\"table_scale\" width=\"600\" bgcolor=\"#ffffff\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td align=\"center\" style=\"margin: 0; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 0;\"> <span> <img class=\"divider\" src=\"images/divider-image.png\" alt=\"divider image\" width=\"600\" height=\"1\" border=\"0\" style=\"display: block;\"> </span> </td>" +
                "</tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"40\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr>" +
                "</tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table class=\"table_scale\" width=\"600\" bgcolor=\"#ffffff\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr>" +
                "<td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\"><table class=\"full\" align=\"left\" width=\"540\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"center\" style=\"padding-bottom: 10px; text-transform: uppercase; font-family: Lucida Sans Unicode; color:#666666; font-size:24px; line-height:34px; mso-line-height-rule: exactly;\"> <span> WHAT ARE YOU WAITING FOR? </span> </td></tr><tr><td align=\"center\" valign=\"top\" style=\"padding-top: 15px;\"><table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#eb5600\" style=\"margin: 0;\"><tbody><tr>" +
                "<td align=\"center\" valign=\"middle\" bgcolor=\"#eb5600\" style=\"padding: 5px 20px; text-transform: uppercase; font-size:14px; line-height: 24px; font-family:Arial, sans-serif; mso-line-height-rule: exactly;\">" +
                "<a href=\"http://www.socioboard.com/Index/Pricing\" target=\"_blank\" style=\"font-weight: normal; color:#ffffff; \"> <b>Try it now!</b> </a></td></tr></tbody></table></td></tr></tbody>" +
                "</table></td><td class=\"spacer\" width=\"30\"></td></tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"40\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td>" +
                "</tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table bgcolor=\"#ededed\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table><table class=\"table_scale\" width=\"600\" bgcolor=\"#ededed\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\">" +
                "<table class=\"full\" align=\"left\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"left\" style=\"margin: 0;  text-transform: uppercase; font-size: 20px; color:#666666; font-family: Lucida Sans Unicode; line-height: 30px;  mso-line-height-rule: exactly;\"> <span> FOLLOW US ONLINE:</span> </td></tr></tbody></table><table width=\"25\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td width=\"100%\" height=\"30\"></td></tr></tbody></table>" +
                "<table class=\"full\" align=\"right\" width=\"300\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td class=\"center\" align=\"right\" style=\"margin: 0; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 100%;\"> <span> <a href=\"https://www.facebook.com/SocioBoard\" target=\"_blank\"><img src=\"http://i.imgur.com/mrfZQKf.png?1\" style=\"max-height: 70px;\"></a> &nbsp;<a href=\"https://twitter.com/Socioboard\" target=\"_blank\"><img src=\"http://i.imgur.com/gSA8HbM.png?1\" style=\"max-height: 70px;\"></a>  &nbsp;" +
                "<a href=\"https://plus.google.com/b/105412765098773776122/105412765098773776122/posts\" target=\"_blank\"><img src=\"http://i.imgur.com/EseCwni.png?1\" style=\"max-height: 70px;\"></a></span> </td></tr></tbody></table></td><td class=\"spacer\" width=\"30\"></td></tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ededed\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr>" +
                "<td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\">" +
                "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table bgcolor=\"#666666\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table><table class=\"table_scale\" width=\"600\" bgcolor=\"#666666\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"600\"><table class=\"full\" align=\"center\" width=\"540\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">" +
                "<tbody><tr><td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:12px ; color:#ededed; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span> We doubled our revenues from the leads acquired with the help of Socioboard. <a target=\"_blank\" href=\"#\" style=\"color:#FDAA7A;\"> - Mahmoudou Sidibe, US</a></span> </td></tr><tr>" +
                "<td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:12px ; color:#ededed; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span> Socioboard has helped us understand our customers better, target them better and increase overall ROI per customer. <a target=\"_blank\" href=\"#\" style=\"color:#FDAA7A;\"> - Sarim Ali, US</a></span> </td></tr><tr><td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:12px ; color:#ededed; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span> Support at Socioboard is excellent, they are online 24/7 and respond to tickets within minutes. <a target=\"_blank\" href=\"#\" style=\"color:#FDAA7A;\"> - Adam Prosmith, UK</a></span> </td></tr>" +
                "<tr><td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:12px ; color:#ededed; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span> Our sales shot over the roof after we started using Socioboard to target customers on Social Media. <a target=\"_blank\" href=\"#\" style=\"color:#FDAA7A;\"> - Christopher Sutch, US</a></span> </td></tr><tr><td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:12px ; color:#ededed; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span> Makes life easy and less cumbersome with smart social inbox. Thanks Socioboard. <a target=\"_blank\" href=\"#\" style=\"color:#FDAA7A;\"> - Maya Ross, UK</a></span> </td></tr></tbody></table></td>" +
                "</tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#666666\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"20\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr>" +
                "<td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table bgcolor=\"#666666\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-top: 1px solid #767373;\">" +
                "<tbody><tr><td width=\"100%\" height=\"20\">&nbsp;</td></tr></tbody></table><table bgcolor=\"#666666\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody>" +
                "<tr><td width=\"100%\" height=\"20\">&nbsp;</td></tr></tbody></table><table bgcolor=\"#f8f8f8\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td>" +
                "</tr></tbody></table><script>$(document).ready(function () {(function (i, s, o, g, r, a, m) {i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {(i[r].q = i[r].q || []).push(arguments)}, i[r].l = 1 * new Date(); a = s.createElement(o),m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)})(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');ga('require', 'displayfeatures');ga('create', 'UA-47199078-1', 'socioboard.com');ga('send', 'pageview');});</script></body></html>";
                UserName = UserName == "N/A" || UserName == "none" ? "" : UserName;
                html = html.Replace("[name]", UserName);
                html = html.Replace("[SenderName]", SenderName);

                string Host = "smtp.mandrillapp.com";
                int port = 587;

                string subject = "You have been invited to Socioboard by " + SenderName;
                string rtn = MailHelper.SendMailByMandrill(Host, port, mandrilEmail, mandrilPass, toEmail, subject, html, SenderName);
                string rtnstr = html + "####" + subject + "####" + UserName + "####" + mandrilEmail + "####" + toEmail;
                if (rtn == "Success")
                {
                    return rtnstr;
                }
                else
                {
                    return null;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.StackTrace);
                return null;
            }
        }
        public static string SendIvitationMailForNew(string UserName, string toEmail, string mandrilEmail, string mandrilPass, string SenderName)
        {
            try
            {
                string html = "<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">" +
                        "<title>Freshmail</title><style type=\"text/css\">" +
                        "html {width: 100%}::-moz-selection {background: #eb5600;color: #fff}::selection {background: #eb5600;color: #fff}body {background-color: #f8f8f8;margin: 0;padding: 0}" +
                        ".ReadMsgBody {width: 100%;background-color: #f8f8f8}.ExternalClass {width: 100%;background-color: #f8f8f8}a {color: #eb5600;text-decoration: none;font-weight: 400;" +
                        "font-style: normal}a:hover {color: #aaa;text-decoration: underline;font-weight: 400;\font-style: normal}a.heading-link {text-decoration: none;font-weight: 400;font-style: normal}" +
                        "a.heading-link:hover {text-decoration: none;font-weight: 400;font-style: normal}p,div {margin: 0!important}table {border-collapse: collapse}@media only screen and (max-width: 640px)" +
                        "{table table {width: 100%!important}td[class=full_width] {width: 100%!important}div[class=div_scale] {width: 440px!important;margin: 0 auto!important}table[class=table_scale] {width: 440px!important;margin: 0 auto!important}" +
                        "td[class=td_scale] {width: 440px!important;margin: 0 auto!important}img[class=img_scale] {width: 100%!important;height: auto!important}img[class=divider] {width: 440px!important;height: 2px!important}" +
                        "table[class=spacer] {display: none!important}td[class=spacer] {display: none!important}td[class=center] {text-align: center!important}table[class=full] {width: 400px!important;margin-left: 20px!important;margin-right: 20px!important}" +
                        "img[class=divider] {width: 100%!important;height: 1px!important}}@media only screen and (max-width: 479px) {table table {width: 100%!important}td[class=full_width] {width: 100%!important}div[class=div_scale] {width: 280px!important;margin: 0 auto!important}" +
                        "table[class=table_scale] {width: 280px!important;margin: 0 auto!important}td[class=td_scale] {width: 280px!important;margin: 0 auto!important}img[class=img_scale] {width: 100%!important;height: auto!important}img[class=divider] {width: 280px!important;height: 2px!important}" +
                        "table[class=spacer] {display: none!important}td[class=spacer] {display: none!important}td[class=center] {text-align: center!important}table[class=full] {width: 240px!important;margin-left: 20px!important;margin-right: 20px!important}" +
                        "img[class=divider] {width: 100%!important;height: 1px!important}}</style><style type=\"text/css\"></style></head>" +
                        "<body bgcolor=\"#f8f8f8\"><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin-top: 20px;\"><tbody><tr><td valign=\"top\" width=\"100%\">" +
                        "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                        "<tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table><table class=\"table_scale\" width=\"600\" bgcolor=\"#ffffff\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                        "<tbody><tr><td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\"><!-- START OF LOGO IMAGE TABLE-->" +
                        "<table class=\"full\" align=\"center\" width=\"255\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr>" +
                        "<td class=\"center\" align=\"left\" style=\"padding: 0px; text-transform: uppercase; font-family: Lucida Sans Unicode; color:#666666; font-size:24px; line-height:34px;\"> <span> <a href=\"#\" style=\"color:#eb5600;\">" +
                        "<img src=\"http://www.socioboard.com/Themes/Socioboard/Contents/img/logo.png\" alt=\"logo\" width=\"250\" height=\"50\" border=\"0\" style=\"display: inline;\"> </a> </span> </td></tr></tbody></table>" +
                        "<!--<table width=\"25\" align=\"left\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td width=\"100%\" height=\"30\"></td></tr></tbody></table> -->" +
                        "</td><td class=\"spacer\" width=\"30\"></td></tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr>" +
                        "<td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr>" +
                        "<td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table class=\"table_scale\" width=\"600\" bgcolor=\"#ffffff\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr>" +
                        "<td width=\"100%\"><table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td class=\"spacer\" width=\"30\"></td><td width=\"540\"><table class=\"full\" align=\"center\" width=\"160\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\">" +
                        "<tbody><tr><td class=\"center\" align=\"center\" style=\"margin: 0; padding: 0px; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 24px;\"> <span> <a target=\"_blank\" href=\"http://www.socioboard.com/\" style=\"color:#eb5600;\"> <img src=\"http://i.imgur.com/Wb75rYQ.png?1\" alt=\"blue\" width=\"600\" height=\"200\" border=\"0\" style=\"display: inline;\">" +
                        "</a></span></td></tr></tbody></table></table></td><td class=\"spacer\" width=\"30\"></td></tr></tbody></table></td></tr></tbody></table><table bgcolor=\"#ffffff\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"40\">&nbsp;</td></tr></tbody></table>" +
                        "</td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table class=\"table_scale\" width=\"600\" bgcolor=\"#dddddd\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                        "<tbody><tr><td width=\"100%\"><table width=\"600\" bgcolor=\"#6E6E6E\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><!--[if gte mso 9]> <v:rect xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\" style=\"width:600px;height:315px;\"> <v:fill type=\"tile\" src=\"http://i.imgur.com/5Udx4T6.png\" color=\"#eb5600\" /> <v:textbox inset=\"0,0,0,0\"> <![endif]-->" +
                        "<tbody><tr><td width=\"600\" valign=\"middle\" style=\"padding: 0px;\"><table class=\"full\" align=\"center\" width=\"540\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr>" +
                        "<tr><td class=\"center\" align=\"center\" style=\"margin: 0; padding-bottom:15px; margin:0; text-transform: uppercase; font-family: Lucida Sans Unicode; font-size: 14px; color: #ffffff; line-height: 20px;mso-line-height-rule: exactly;\"> <span>SocioQueue has unique features which you won't find anywhere else. Best part is its all available in our open-source package.</span></td></tr>" +
                        "<tr><td style=\"padding-top: 30px;\"><table width=\"100%\" border=\"0\"  cellspacing=\"0\" cellpadding=\"0\"><tbody><tr><td width=\"100\" class=\"img\" style=\"font-size:0pt; line-height:0pt; text-align:left\"><a target=\"_blank\" href=\"#\"><img src=\"http://i.imgur.com/cEIuVLn.png\" width=\"60\" height=\"56\" border=\"0\" alt=\"\"></a></td>" +
                        "<td class=\"text-small\" style=\"font-family:Tahoma; font-size:13px; line-height:18px; text-align:left; color:#ffffff\"><div class=\"h2-2\" style=\"font-family:Tahoma, sans-serif; font-size:16px; line-height:18px; font-weight:bold; padding: 0 0 10; color:#ffffff\">Custom settings</div>Queue is now highly customizable profile by profile and is highly suitable for audiences with unique taste." +
                        "</td></tr></tbody></table> </td></tr><tr><td style=\"padding-top: 30px;\"><table width=\"100%\" border=\"0\"  cellspacing=\"0\" cellpadding=\"0\"><tbody><tr><td width=\"100\" class=\"img\" style=\"font-size:0pt; line-height:0pt; text-align:left\"><a target=\"_blank\" href=\"#\">" +
                        "<img src=\"http://i.imgur.com/fGr68Yy.png?1\" width=\"60\" height=\"56\" border=\"0\" alt=\"\"></a></td><td class=\"text-small\" style=\"font-family:Tahoma; font-size:13px; line-height:18px; text-align:left; color:#ffffff\"><div class=\"h2-2\" style=\"font-family:Tahoma, sans-serif; font-size:16px; line-height:18px; font-weight:bold; padding: 0 0 10; color:#ffffff\">" +
                        "Smart timeline</div>See your posts as draft and edit and fill gaps as required before firing your arrows.</td></tr></tbody></table></td></tr><tr><td style=\"padding-top: 30px;\"><table width=\"100%\" border=\"0\"  cellspacing=\"0\" cellpadding=\"0\"><tbody><tr><td width=\"100\" class=\"img\" style=\"font-size:0pt; line-height:0pt; text-align:left\">" +
                        "<a target=\"_blank\" href=\"#\"><img src=\"http://i.imgur.com/iLJLF97.png?1\" width=\"60\" height=\"56\" border=\"0\" alt=\"\"></a></td><td class=\"text-small\" style=\"font-family:Tahoma; font-size:13px; line-height:18px; text-align:left; color:#ffffff\">" +
                        "<div class=\"h2-2\" style=\"font-family:Tahoma, sans-serif; font-size:16px; line-height:18px; font-weight:bold; padding: 0 0 10; color:#ffffff\">Set and Go!</div>Schedule your posts for profiles and the content gets posted automatically from the queue.</td></tr></tbody></table> </td></tr>" +
                        "<tr><td align=\"center\" valign=\"middle\" style=\"padding-top: 20px;\"><table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#ffffff\" style=\"margin: 0;\"><tbody><tr>" +
                        "<td align=\"center\" valign=\"middle\" bgcolor=\"#ffffff\" style=\"padding: 8px 20px; text-transform: uppercase; color:#666666; font-size:18px ; color:#ffffff; font-family: Helvetica, Arial, sans-serif; line-height: 28px; mso-line-height-rule: exactly;\">" +
                        "<a href=\"http://www.socioboard.com\" target=\"_blank\" style=\"font-weight: normal; color:#444444; \"> FIND OUT MORE </a> </td></tr></tbody></table></td></tr>" +
                        "<tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table></td></tr><!--[if gte mso 9]> </v:textbox> </v:rect> <![endif]--></tbody></table></td></tr></tbody>" +
                        "</table></td></tr></tbody></table></td></tr></tbody></table><table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\">" +
                        "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\"><table bgcolor=\"#dddddd\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                        "<tbody><!-- START OF BUTTON--><tr><td align=\"center\" valign=\"middle\" style=\"padding-top: 20px;\"><table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"style=\"margin: 0;\"><tbody><tr>" +
                        "<td width=\"100\" class=\"img\" style=\"font-size:0pt; line-height:0pt; text-align:left\"><a target=\"_blank\" href=\"#\"><img src=\"http://i.imgur.com/yubWZFL.png\" width=\"60\" height=\"56\" border=\"0\" alt=\"\"></a></td></tr></tbody></table></td></tr>" +
                        "<tr><td align=\"center\" valign=\"middle\" style=\"padding-top: 20px;\"><table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"style=\"margin: 0;\"><tbody><tr><td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:14px ; color:#000000; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span>Stay connected for tips and tricks</span>" +
                        "</td></tr></tbody></table></td></tr><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr><tr><td class=\"center\" align=\"center\" style=\"margin: 0; font-size:14px ; color:#aaaaaa; font-family: Helvetica, Arial, sans-serif; line-height: 100%;\"> <span> <a href=\"https://www.facebook.com/SocioBoard\" target=\"_blank\"><img src=\"http://i.imgur.com/mrfZQKf.png?1\" style=\"max-height: 50px;\">" +
                        "</a> &nbsp;<a href=\"https://twitter.com/Socioboard\" target=\"_blank\"><img src=\"http://i.imgur.com/gSA8HbM.png?1\" style=\"max-height: 50px;\"></a>&nbsp;<a href=\"https://plus.google.com/b/105412765098773776122/105412765098773776122/posts\" target=\"_blank\"><img src=\"http://i.imgur.com/EseCwni.png?1\" style=\"max-height: 50px;\"></a></span></td></tr>" +
                        "<tr><td align=\"center\" valign=\"middle\" style=\"padding-top: 20px;\"><table border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"style=\"margin: 0;\"><tbody></tbody></table></td></tr></tbody></table><table bgcolor=\"#dddddd\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">" +
                        "<tbody><tr><td class=\"center\" align=\"center\" style=\"margin: 0;  font-size:14px ; color:#000000; font-family: Helvetica, Arial, sans-serif; line-height: 18px;\"> <span>L V Complex, 2nd Floor, No.58, 7th Block, 80 Feet Road, Koramangala – 560095 Bangalore, Karnataka, India</span> </td></tr><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody></table>" +
                        "</td></tr></tbody></table></td></tr></tbody></table>   <table align=\"center\" bgcolor=\"#f8f8f8\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td valign=\"top\" width=\"100%\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\">" +
                        "<table bgcolor=\"#666666\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-top: 1px solid #767373;\"><tbody><tr><td width=\"100%\" height=\"20\">&nbsp;</td></tr></tbody></table>" +
                        "<table bgcolor=\"#666666\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"20\">&nbsp;</td></tr></tbody></table>" +
                        "<table bgcolor=\"#f8f8f8\" class=\"table_scale\" width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tbody><tr><td width=\"100%\" height=\"30\">&nbsp;</td></tr></tbody>" +
                        "</table></td></tr></tbody></table></td></tr></tbody></table></body></html>";
                UserName = UserName == "N/A" || UserName == "none" ? "" : UserName;
                html = html.Replace("[name]", UserName);
                html = html.Replace("[SenderName]", SenderName);

                string Host = "smtp.mandrillapp.com";
                int port = 587;

                string subject = "Schedule and Automate your social media posts with SocioQueue from Socioboard";
                string rtn = MailHelper.SendMailByMandrill(Host, port, mandrilEmail, mandrilPass, toEmail, subject, html, SenderName);
                string rtnstr = html + "####" + subject + "####" + UserName + "####" + mandrilEmail + "####" + toEmail;
                if (rtn == "Success")
                {
                    return rtnstr;
                }
                else
                {
                    return null;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.StackTrace);
                return null;
            }
        }

        public static string SendAccountExpiryMail(string UserName, string toEmail, string MandrillEmail, string MandrillPass, string SenderName)
        {
            string html = "";
            string Host = "smtp.mandrillapp.com";
            int port = 587;
            string subject = "Account Expiry Mail";
            string rtn = MailHelper.SendMailByMandrill(Host, port, MandrillEmail, MandrillPass, toEmail, subject, html, SenderName);
            if (rtn == "Success")
            {
                return rtn;
            }
            else
            {
                return null;
            }

            return "";
        }
    }
}
