//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocioBoardAccountEpiryMailSender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/User.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_User_User {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_User_User"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/AdminUserDetails.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_AdminUserDetails_AdminUserDetails {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_AdminUserDetails_AdminUserDetails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TwitterAccount.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_TwitterAccount_TwitterAccount {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_TwitterAccount_TwitterAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FacebookAccount.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_FacebookAccount_FacebookAccount {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_FacebookAccount_FacebookAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/InboxMessages.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_InboxMessages_InboxMessages {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_InboxMessages_InboxMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TwitterDirectMessages.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_TwitterDirectMessages_TwitterDirectMessages {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_TwitterDirectMessages_TwitterDirectMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/GroupReports.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_GroupReports_GroupReports {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_GroupReports_GroupReports"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/ScheduledMessage.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_ScheduledMessage_ScheduledMessage {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_ScheduledMessage_ScheduledMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Team.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_Team_Team {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_Team_Team"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/Groups.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_Groups_Groups {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_Groups_Groups"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/TeamMemberProfile.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_TeamMemberProfile_TeamMemberProfile {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_TeamMemberProfile_TeamMemberProfile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/InstagramAccount.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_InstagramAccount_InstagramAccount {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_InstagramAccount_InstagramAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FacebookReport.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_FacebookReport_FacebookReport {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_FacebookReport_FacebookReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/Services/FacebookGroupReport.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_FacebookGroupReport_FacebookGroupReport {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_FacebookGroupReport_FacebookGroupReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6361/services/InstagramReports.asmx")]
        public string SocioBoardAccountEpiryMailSender_Api_InstagramReports_InstagramReports {
            get {
                return ((string)(this["SocioBoardAccountEpiryMailSender_Api_InstagramReports_InstagramReports"]));
            }
        }
    }
}
